name: deopling COdaLeague

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deopling to Heroku
        id: deploy
        uses: akhileshns/heroku-deploy@v3.6.8

        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "codaleague"
          heroku_email: "mayurbhowad10924@gmail.com"